[package]
name = "space_powder_marketplace"
version = "0.1.0"

[addresses]
aptos_framework = "0x1"
space_powder_marketplace = "1f7a4d05dc1ff9434ed2dac4f123d44ed27cc7248ef92ff39c1d87b8f029d741"

[dependencies]
AptosFramework = { local = "/Users/nambawan/Documents/Aptos/aptos-core/aptos-move/framework/aptos-framework"}
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
