[package]
name = "space_powder_marketplace"
version = "0.1.0"

[addresses]
AptosFramework = "0x1"
SpacePowderMarketplace = "d8928bd1e4dcf324fc430c19ce9f88564df97a8acfa83a346232f281f997a943"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
