[package]
name = "space_powder_marketplace"
version = "0.1.1"

[addresses]
aptos_framework = "0x1"
space_powder_marketplace = "e555ea6e4621b4cc8b526d5b4959e832db4a341e718551cf1d476bef497b6b8a"

[dependencies]
AptosFramework = { local = "/Users/nambawan/Documents/Aptos/aptos-core/aptos-move/framework/aptos-framework"}
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
