[package]
name = "space_powder_marketplace"
version = "0.1.0"

[addresses]
AptosFramework = "0x1"
SpacePowderMarketplace = "0x931c9ed97ad833da1f543da35459c508fdd4d429e13cd146fff4c7a9b545dfca"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
